export const mlbbHeaders = [
  { name: 'PLAYER', width: 'min-w-[200px]', alt: 'Player & Team' },
  { name: 'HERO', width: 'min-w-[130px]', alt: 'Most Played Hero' },
  { name: 'GMS', width: 'min-w-[50px]', alt: 'Total Games' },
  { name: 'MVPS', width: 'min-w-[50px]', alt: 'Total MVPs' },
  { name: 'R', width: 'min-w-[50px]', alt: 'Average Rating' },
  { name: 'KPG', width: 'min-w-[50px]', alt: 'Kills per Game' },
  { name: 'DPG', width: 'min-w-[50px]', alt: 'Deaths per Game' },
  { name: 'APG', width: 'min-w-[50px]', alt: 'Assists per Game' },
  { name: 'GLD', width: 'min-w-[80px]', alt: 'Total Gold' },
  { name: 'HDMG', width: 'min-w-[80px]', alt: 'Total Hero Damage' },
  { name: 'TDMG', width: 'min-w-[80px]', alt: 'Total Turret Damage' },
  { name: 'DMGT', width: 'min-w-[80px]', alt: 'Total Damage Taken' },
  { name: 'TF', width: 'min-w-[50px]', alt: 'Teamfight Participation' },
  { name: 'K', width: 'min-w-[50px]', alt: 'Total Kills' },
  { name: 'D', width: 'min-w-[50px]', alt: 'Total Deaths' },
  { name: 'A', width: 'min-w-[50px]', alt: 'Total Assists' },
  { name: 'LS', width: 'min-w-[50px]', alt: 'Lords Slain' },
  { name: 'TS', width: 'min-w-[50px]', alt: 'Turtles Slain' }
];

export const valoHeaders = [
  { name: 'PLAYER', width: 'min-w-[200px]', alt: 'Player & Team' },
  { name: 'AGENT', width: 'min-w-[100px]', alt: 'Most Played Agent' },
  { name: 'GMS', width: 'min-w-[50px]', alt: 'Total Games' },
  { name: 'RNDS', width: 'min-w-[50px]', alt: 'Total Rounds' },
  { name: 'MVPS', width: 'min-w-[50px]', alt: 'Total MVPs' },
  { name: 'ACS', width: 'min-w-[50px]', alt: 'Average Combat Score' },
  { name: 'KPG', width: 'min-w-[50px]', alt: 'Kills per Game' },
  { name: 'DPG', width: 'min-w-[50px]', alt: 'Deaths per Game' },
  { name: 'APG', width: 'min-w-[50px]', alt: 'Assists per Game' },
  { name: 'KPR', width: 'min-w-[50px]', alt: 'Kills per Round' },
  { name: 'DPR', width: 'min-w-[50px]', alt: 'Deaths per Round' },
  { name: 'APR', width: 'min-w-[50px]', alt: 'Assists per Round' },
  { name: 'K', width: 'min-w-[50px]', alt: 'Total Kills' },
  { name: 'D', width: 'min-w-[50px]', alt: 'Total Deaths' },
  { name: 'A', width: 'min-w-[50px]', alt: 'Total Assists' },
  { name: 'FB', width: 'min-w-[50px]', alt: 'Total First Bloods' },
  { name: 'PL', width: 'min-w-[50px]', alt: 'Total Plants' },
  { name: 'DF', width: 'min-w-[50px]', alt: 'Total Defuses' }
];
